export { default as Home } from "./home"
export { default as Login } from "./login"
export { default as Register } from "./register"
export { default as RegisterSuccess } from "./registerSuccess"
export { default as Profile } from "./profile"
export { default as Links} from "./links"
export { default as Appearance } from "./appearance"
export { default as User } from "./user"
