export { default as Login } from "./login"
export { default as Register } from "./register"
export { default as Profile } from "./profile"
export { default as Links} from "./links"
export { default as Appearance} from "./appearance"